import type { Scent } from './types'

export const SEED_SCENTS: Scent[] = [
  { id: 'aesop-hwyl', brand: 'Aesop', name: 'Hwyl', families: ['woody','smoky'],
    ingredientKey: 'smoke,forest',
    accords: [{name:'smoke',strength:.9},{name:'woody',strength:.7},{name:'incense',strength:.6}],
    notes: [{name:'Cypress',layer:'top'},{name:'Frankincense',layer:'heart'},{name:'Vetiver',layer:'base'}] },
  { id: 'aesop-aurner', brand: 'Aesop', name: 'Aurner', families: ['aromatic','woody'],
    ingredientKey: 'cedar,plant',
    accords: [{name:'aromatic',strength:.8},{name:'woody',strength:.6}],
    notes: [{name:'Geranium',layer:'top'},{name:'Chamomile',layer:'heart'},{name:'Cedar',layer:'base'}] },
  { id: 'tomford-noir', brand: 'Tom Ford', name: 'Noir', year: 2012, families: ['amber','smoky'],
    ingredientKey: 'smoke,incense',
    accords: [{name:'leather',strength:.62},{name:'amber',strength:.54},{name:'iris',strength:.4},{name:'spicy',strength:.33}],
    notes: [{name:'Bergamot',layer:'top'},{name:'Pink Pepper',layer:'top'},{name:'Iris',layer:'heart'},{name:'Nutmeg',layer:'heart'},{name:'Amber',layer:'base'},{name:'Leather',layer:'base'},{name:'Vanilla',layer:'base'}] },
  { id: 'lelabo-santal33', brand: 'Le Labo', name: 'Santal 33', families: ['woody'],
    ingredientKey: 'sandalwood,wood',
    accords: [{name:'sandalwood',strength:.92},{name:'leather',strength:.5},{name:'cardamom',strength:.45}],
    notes: [{name:'Cardamom',layer:'top'},{name:'Violet',layer:'heart'},{name:'Sandalwood',layer:'base'},{name:'Cedar',layer:'base'}] },
  { id: 'byredo-mojaveghost', brand: 'Byredo', name: 'Mojave Ghost', families: ['woody','floral'],
    ingredientKey: 'desert,sand',
    accords: [{name:'woody',strength:.7},{name:'floral',strength:.55},{name:'amber',strength:.4}],
    notes: [{name:'Ambrette',layer:'top'},{name:'Magnolia',layer:'heart'},{name:'Sandalwood',layer:'base'}] },
  { id: 'dior-ambrenuit', brand: 'Dior', name: 'Ambre Nuit', families: ['amber'],
    ingredientKey: 'amber,rose',
    accords: [{name:'amber',strength:.8},{name:'rose',strength:.5}],
    notes: [{name:'Bergamot',layer:'top'},{name:'Rose',layer:'heart'},{name:'Ambergris',layer:'base'}] },
  { id: 'dior-grisdior', brand: 'Dior', name: 'Gris Dior', families: ['aromatic','floral'],
    ingredientKey: 'lavender,citrus',
    accords: [{name:'aromatic',strength:.7},{name:'citrus',strength:.5}],
    notes: [{name:'Bergamot',layer:'top'},{name:'Lavender',layer:'heart'},{name:'Patchouli',layer:'base'}] },
  { id: 'diptyque-vetyverio', brand: 'Diptyque', name: 'Vetyverio', families: ['woody','aromatic'],
    ingredientKey: 'vetiver,grass',
    accords: [{name:'vetiver',strength:.85},{name:'earthy',strength:.6}],
    notes: [{name:'Citrus',layer:'top'},{name:'Geranium',layer:'heart'},{name:'Vetiver',layer:'base'}] },
  { id: 'malingoetz-cannabis', brand: 'Malin + Goetz', name: 'Cannabis', families: ['aromatic'],
    ingredientKey: 'cannabis,leaf',
    accords: [{name:'green',strength:.8},{name:'aromatic',strength:.6}],
    notes: [{name:'Lime',layer:'top'},{name:'Cannabis Accord',layer:'heart'},{name:'Patchouli',layer:'base'}] },
  { id: 'cave-sloanetones', brand: 'CAVE', name: 'Sloane Tones', families: ['smoky','woody'],
    ingredientKey: 'leather,dark', needsEnrichment: true,
    accords: [{name:'leather',strength:.6}],
    notes: [{name:'Leather',layer:'base'}] },
  { id: 'franckolivier-nighttouch', brand: 'Franck Olivier', name: 'Night Touch', families: ['amber','woody'],
    ingredientKey: 'amber,wood', needsEnrichment: true,
    accords: [{name:'amber',strength:.6}],
    notes: [{name:'Amber',layer:'base'}] },
  { id: 'aramic-heart', brand: 'Aramic', name: 'Heart', families: ['amber'],
    ingredientKey: 'rose,red', needsEnrichment: true,
    accords: [{name:'amber',strength:.5}],
    notes: [{name:'Rose',layer:'heart'}] },
  { id: 'aramic-heaven', brand: 'Aramic', name: 'Heaven', families: ['fresh'],
    ingredientKey: 'sky,clouds', needsEnrichment: true,
    accords: [{name:'fresh',strength:.5}],
    notes: [{name:'Citrus',layer:'top'}] },
  { id: 'reef-summerpeach', brand: 'Reef', name: 'Summer Peach', families: ['fresh','gourmand'],
    ingredientKey: 'peach,fruit', needsEnrichment: true,
    accords: [{name:'fruity',strength:.6}],
    notes: [{name:'Peach',layer:'top'}] },
  { id: 'ghissah-hudson', brand: 'Ghissah', name: 'Hudson', families: ['woody','amber'],
    ingredientKey: 'oud,wood', needsEnrichment: true,
    accords: [{name:'woody',strength:.6}],
    notes: [{name:'Oud',layer:'base'}] },
]
