import type { Scent } from './types'

export const SEED_SCENTS: Scent[] = [
  { id: 'aesop-hwyl', brand: 'Aesop', name: 'Hwyl', families: ['woody','smoky'],
    ingredientKey: 'smoke,forest',
    accords: [{name:'smoke',strength:.9},{name:'woody',strength:.7},{name:'incense',strength:.6}],
    notes: [{name:'Cypress',layer:'top'},{name:'Frankincense',layer:'heart'},{name:'Vetiver',layer:'base'}],
    profile: { warmth:7, freshness:3, sweet:1, dark:8, floral:0, spicy:3, green:5, woody:9, smoky:9, musky:2, resinous:7, projection:5, longevity:8, weight:'heavy' },
    tags: { occasions:['solo','gallery','reflection'], weather:['cold','overcast','rainy','fog'], energy:['introspective','calm'], time:['afternoon','evening'] },
    season:['autumn','winter'], mood:'Meditative', aura:'#4a5240',
    blurb:'Smoke rising through wet cypress. A Japanese temple at dusk.',
    application:'Inner wrists and behind ears, let the incense drift naturally.',
    effect:'Quiet authority. People lean in without knowing why.' },

  { id: 'aesop-aurner', brand: 'Aesop', name: 'Aurner', families: ['aromatic','woody'],
    ingredientKey: 'cedar,plant',
    accords: [{name:'aromatic',strength:.8},{name:'woody',strength:.6}],
    notes: [{name:'Geranium',layer:'top'},{name:'Chamomile',layer:'heart'},{name:'Cedar',layer:'base'}],
    profile: { warmth:5, freshness:6, sweet:3, dark:3, floral:5, spicy:4, green:4, woody:6, smoky:0, musky:2, resinous:1, projection:4, longevity:6, weight:'medium' },
    tags: { occasions:['work','brunch','meeting'], weather:['mild','overcast','cool'], energy:['calm','focused','balanced'], time:['morning','afternoon'] },
    season:['spring','autumn'], mood:'Calm', aura:'#8b7d6b',
    blurb:'Herbal tea in a sunlit studio. Linen and warm wood.',
    application:'Wrists and chest, a gentle radius of calm.',
    effect:'Approachable intelligence. Quietly impressive.' },

  { id: 'tomford-noir', brand: 'Tom Ford', name: 'Noir', year: 2012, families: ['amber','smoky'],
    ingredientKey: 'smoke,incense',
    accords: [{name:'leather',strength:.62},{name:'amber',strength:.54},{name:'iris',strength:.4},{name:'spicy',strength:.33}],
    notes: [{name:'Bergamot',layer:'top'},{name:'Pink Pepper',layer:'top'},{name:'Iris',layer:'heart'},{name:'Nutmeg',layer:'heart'},{name:'Amber',layer:'base'},{name:'Leather',layer:'base'},{name:'Vanilla',layer:'base'}] },

  { id: 'lelabo-santal33', brand: 'Le Labo', name: 'Santal 33', families: ['woody'],
    ingredientKey: 'sandalwood,wood',
    accords: [{name:'sandalwood',strength:.92},{name:'leather',strength:.5},{name:'cardamom',strength:.45}],
    notes: [{name:'Cardamom',layer:'top'},{name:'Violet',layer:'heart'},{name:'Sandalwood',layer:'base'},{name:'Cedar',layer:'base'}] },

  { id: 'byredo-mojaveghost', brand: 'Byredo', name: 'Mojave Ghost', families: ['woody','floral'],
    ingredientKey: 'desert,sand',
    accords: [{name:'woody',strength:.7},{name:'floral',strength:.55},{name:'amber',strength:.4}],
    notes: [{name:'Ambrette',layer:'top'},{name:'Magnolia',layer:'heart'},{name:'Sandalwood',layer:'base'}],
    profile: { warmth:4, freshness:7, sweet:4, dark:1, floral:4, spicy:0, green:2, woody:5, smoky:0, musky:8, resinous:1, projection:4, longevity:5, weight:'light' },
    tags: { occasions:['date','brunch','travel','beach'], weather:['warm','hot','mild','sunny'], energy:['relaxed','romantic'], time:['morning','afternoon'] },
    season:['spring','summer'], mood:'Ethereal', aura:'#d4c5a9',
    blurb:'Desert light through white curtains. Clean skin after the ocean.',
    application:'Neck, inner elbows, and hair, this one floats.',
    effect:'Magnetic softness. The scent people ask about.' },

  { id: 'dior-ambrenuit', brand: 'Dior', name: 'Ambre Nuit', families: ['amber'],
    ingredientKey: 'amber,rose',
    accords: [{name:'amber',strength:.8},{name:'rose',strength:.5}],
    notes: [{name:'Bergamot',layer:'top'},{name:'Rose',layer:'heart'},{name:'Ambergris',layer:'base'}],
    profile: { warmth:9, freshness:1, sweet:4, dark:8, floral:3, spicy:7, green:0, woody:6, smoky:6, musky:2, resinous:5, projection:7, longevity:9, weight:'heavy' },
    tags: { occasions:['date','dinner','event'], weather:['cold','cool'], energy:['confident','bold','romantic'], time:['evening','night'] },
    season:['autumn','winter'], mood:'Seductive', aura:'#6b3a3a',
    blurb:'A dark rose crushed in amber resin. Candlelit and close.',
    application:'Neck, chest, and inner wrists, let body heat amplify.',
    effect:'Irresistible gravity. The closer they get, the more they want.' },

  { id: 'dior-grisdior', brand: 'Dior', name: 'Gris Dior', families: ['aromatic','floral'],
    ingredientKey: 'lavender,citrus',
    accords: [{name:'aromatic',strength:.7},{name:'citrus',strength:.5}],
    notes: [{name:'Bergamot',layer:'top'},{name:'Lavender',layer:'heart'},{name:'Patchouli',layer:'base'}],
    profile: { warmth:5, freshness:6, sweet:2, dark:3, floral:6, spicy:2, green:3, woody:4, smoky:0, musky:3, resinous:2, projection:6, longevity:7, weight:'medium' },
    tags: { occasions:['work','meeting','dinner','event'], weather:['mild','cool','overcast'], energy:['confident','balanced','sharp'], time:['morning','afternoon','evening'] },
    season:['spring','autumn'], mood:'Refined', aura:'#9e8b7e',
    blurb:'A tailored grey suit. Rose petals on marble.',
    application:'Wrists and behind ears, classic deployment for a classic scent.',
    effect:'Polished authority. Parisian restraint.' },

  { id: 'diptyque-vetyverio', brand: 'Diptyque', name: 'Vetyverio', families: ['woody','aromatic'],
    ingredientKey: 'vetiver,grass',
    accords: [{name:'vetiver',strength:.85},{name:'earthy',strength:.6}],
    notes: [{name:'Citrus',layer:'top'},{name:'Geranium',layer:'heart'},{name:'Vetiver',layer:'base'}],
    profile: { warmth:3, freshness:8, sweet:1, dark:2, floral:3, spicy:3, green:8, woody:7, smoky:2, musky:5, resinous:0, projection:4, longevity:5, weight:'light' },
    tags: { occasions:['work','casual','brunch','meeting'], weather:['mild','warm','sunny'], energy:['calm','balanced','focused'], time:['morning','afternoon'] },
    season:['spring','summer'], mood:'Grounded', aura:'#6a7a5e',
    blurb:'Wet grass and grapefruit zest. A Parisian garden at ten in the morning.',
    application:'Wrists, inner elbows, and behind ears, spray generously, this sits close to skin.',
    effect:'Effortless refinement. Clean, earthy intelligence that never tries too hard.' },

  { id: 'malingoetz-cannabis', brand: 'Malin + Goetz', name: 'Cannabis', families: ['aromatic'],
    ingredientKey: 'cannabis,leaf',
    accords: [{name:'green',strength:.8},{name:'aromatic',strength:.6}],
    notes: [{name:'Lime',layer:'top'},{name:'Cannabis Accord',layer:'heart'},{name:'Patchouli',layer:'base'}],
    profile: { warmth:4, freshness:6, sweet:1, dark:3, floral:0, spicy:4, green:7, woody:5, smoky:1, musky:2, resinous:1, projection:4, longevity:5, weight:'light' },
    tags: { occasions:['casual','weekend','social','festival'], weather:['warm','mild','humid'], energy:['relaxed','social','nonchalant'], time:['afternoon','evening'] },
    season:['summer','autumn'], mood:'Nonchalant', aura:'#4f6b4a',
    blurb:'Sunday in the park. Black pepper and easy confidence.',
    application:'Wrists and back of neck, casual, effortless placement.',
    effect:'Cool without trying. The friend everyone gravitates toward.' },

  { id: 'cave-sloanetones', brand: 'CAVE', name: 'Sloane Tones', families: ['smoky','woody'],
    ingredientKey: 'leather,dark',
    accords: [{name:'leather',strength:.6}],
    notes: [{name:'Osmanthus',layer:'top'},{name:'Tuberose',layer:'heart'},{name:'Agarwood',layer:'base'},{name:'Cedar',layer:'base'}],
    profile: { warmth:8, freshness:2, sweet:6, dark:6, floral:5, spicy:3, green:1, woody:7, smoky:2, musky:3, resinous:3, projection:7, longevity:8, weight:'heavy' },
    tags: { occasions:['event','dinner','date'], weather:['cool','cold','overcast'], energy:['confident','romantic','bold'], time:['evening','night'] },
    season:['autumn','winter'], mood:'Luxurious', aura:'#6b5a7e',
    blurb:'Agarwood smoke through tuberose. Sloane Street after dark.',
    application:'Behind ears and chest, let the oud and florals interplay at body temperature.',
    effect:'Understated opulence. London luxury without the logo.' },

  { id: 'franckolivier-nighttouch', brand: 'Franck Olivier', name: 'Night Touch', families: ['amber','woody'],
    ingredientKey: 'amber,wood',
    accords: [{name:'amber',strength:.6}],
    notes: [{name:'Bergamot',layer:'top'},{name:'Jasmine',layer:'heart'},{name:'Vetiver',layer:'base'},{name:'Musk',layer:'base'}],
    profile: { warmth:3, freshness:8, sweet:5, dark:1, floral:3, spicy:1, green:3, woody:3, smoky:0, musky:6, resinous:0, projection:6, longevity:5, weight:'light' },
    tags: { occasions:['night out','party','date','social'], weather:['warm','hot','humid'], energy:['energetic','bold','social'], time:['evening','night'] },
    season:['spring','summer'], mood:'Electric', aura:'#3a4a6b',
    blurb:'Neon reflections on wet pavement. Summer night velocity.',
    application:'Neck and forearms, designed to cut through warm air.',
    effect:'Head-turning freshness. High-energy magnetism.' },

  { id: 'aramic-heart', brand: 'Aramic', name: 'Heart', families: ['amber'],
    ingredientKey: 'rose,red', needsEnrichment: true,
    accords: [{name:'amber',strength:.5}],
    notes: [{name:'Rose',layer:'heart'}] },

  { id: 'aramic-heaven', brand: 'Aramic', name: 'Heaven', families: ['fresh'],
    ingredientKey: 'sky,clouds', needsEnrichment: true,
    accords: [{name:'fresh',strength:.5}],
    notes: [{name:'Citrus',layer:'top'}] },

  { id: 'reef-summerpeach', brand: 'Reef', name: 'Summer Peach', families: ['fresh','gourmand'],
    ingredientKey: 'peach,fruit',
    accords: [{name:'fruity',strength:.6}],
    notes: [{name:'Peach',layer:'top'},{name:'Iris',layer:'heart'},{name:'Yerba Mate',layer:'base'}],
    profile: { warmth:3, freshness:9, sweet:6, dark:0, floral:2, spicy:0, green:6, woody:1, smoky:0, musky:1, resinous:0, projection:3, longevity:4, weight:'light' },
    tags: { occasions:['brunch','casual','beach','daytime'], weather:['hot','warm','sunny'], energy:['light','energetic','relaxed'], time:['morning','afternoon'] },
    season:['spring','summer'], mood:'Bright', aura:'#c4956a',
    blurb:'First bite of summer. Sun on bare arms. Uncomplicated joy.',
    application:'Wrists, neck, and liberally, this one is gentle and close-range.',
    effect:'Disarming warmth. A smile you can smell.' },

  { id: 'ghissah-hudson', brand: 'Ghissah', name: 'Hudson', families: ['woody','amber'],
    ingredientKey: 'oud,wood',
    accords: [{name:'woody',strength:.6}],
    notes: [{name:'Rose',layer:'heart'},{name:'White Flowers',layer:'heart'},{name:'Saffron',layer:'heart'},{name:'Amber',layer:'base'},{name:'Musk',layer:'base'},{name:'Tonka Bean',layer:'base'}],
    profile: { warmth:7, freshness:4, sweet:7, dark:3, floral:6, spicy:3, green:0, woody:2, smoky:0, musky:6, resinous:3, projection:6, longevity:7, weight:'medium' },
    tags: { occasions:['date','dinner','event','social'], weather:['mild','cool','cold'], energy:['romantic','confident'], time:['afternoon','evening','night'] },
    season:['spring','autumn','winter'], mood:'Romantic', aura:'#8a5e6a',
    blurb:'Saffron-dusted rose and ripe fruit. A love letter sealed in amber.',
    application:'Neck and inner wrists, let the saffron bloom at body heat. Two to three sprays.',
    effect:'Warm magnetism. The scent that draws people closer without them realising why.' },

  { id: 'iaq-spanishtobacco', brand: 'Ibrahim Al Qurashi', name: 'Spanish Tobacco', families: ['amber','spicy'],
    ingredientKey: 'tobacco,saffron',
    accords: [{name:'tobacco',strength:.8},{name:'amber',strength:.6},{name:'saffron',strength:.5}],
    notes: [{name:'Aquatic',layer:'top'},{name:'Saffron',layer:'heart'},{name:'Cocoa',layer:'heart'},{name:'Iris',layer:'heart'},{name:'Tobacco',layer:'base'},{name:'Amber',layer:'base'}],
    profile: { warmth:9, freshness:2, sweet:6, dark:9, floral:1, spicy:6, green:0, woody:5, smoky:4, musky:2, resinous:4, projection:8, longevity:10, weight:'heavy' },
    tags: { occasions:['event','dinner','date'], weather:['cold','cool'], energy:['bold','confident','commanding'], time:['evening','night'] },
    season:['autumn','winter'], mood:'Opulent', aura:'#5c3d2e',
    blurb:'Leather armchair in a private library. Saffron smoke and old money.',
    application:'Chest and behind ears only, this beast projects. Less is power.',
    effect:'Unforgettable presence. Rooms remember you.' },

  { id: 'lelabo-tabac26', brand: 'Le Labo', name: 'Tabac 26', families: ['woody','smoky'],
    ingredientKey: 'tobacco,hay',
    accords: [{name:'tobacco',strength:.7},{name:'woody',strength:.6},{name:'hay',strength:.5}],
    notes: [{name:'Bay Leaf',layer:'top'},{name:'Fig',layer:'heart'},{name:'Hay',layer:'heart'},{name:'Tobacco',layer:'base'},{name:'Cedar',layer:'base'}],
    profile: { warmth:7, freshness:3, sweet:2, dark:6, floral:0, spicy:3, green:4, woody:8, smoky:3, musky:1, resinous:2, projection:5, longevity:7, weight:'medium' },
    tags: { occasions:['reading','gallery','solo'], weather:['cold','overcast','rainy'], energy:['introspective','calm'], time:['afternoon'] },
    season:['autumn','winter'], mood:'Intellectual', aura:'#6b5e4f',
    blurb:'A dog-eared novel. Dried fig leaves and afternoon light.',
    application:'Wrists and inner elbows, a personal aura, not a broadcast.',
    effect:'Quiet depth. The scent of someone with something to say.' },

  { id: 'tomford-noirextreme', brand: 'Tom Ford', name: 'Noir Extreme', families: ['amber','spicy','gourmand'],
    ingredientKey: 'spice,vanilla',
    accords: [{name:'amber',strength:.7},{name:'spicy',strength:.65},{name:'vanilla',strength:.6}],
    notes: [{name:'Cardamom',layer:'top'},{name:'Nutmeg',layer:'top'},{name:'Saffron',layer:'heart'},{name:'Kulfi',layer:'heart'},{name:'Rose',layer:'heart'},{name:'Vanilla',layer:'base'},{name:'Amber',layer:'base'}],
    profile: { warmth:10, freshness:1, sweet:8, dark:7, floral:2, spicy:9, green:0, woody:3, smoky:1, musky:2, resinous:4, projection:8, longevity:9, weight:'heavy' },
    tags: { occasions:['date','dinner','event','night out'], weather:['cold','cool'], energy:['bold','confident','commanding'], time:['evening','night'] },
    season:['autumn','winter'], mood:'Commanding', aura:'#2e2e2e',
    blurb:'Cardamom kulfi at midnight. Velvet and gold.',
    application:'Chest and one wrist, let body heat do the work. Two sprays maximum.',
    effect:'Devastating. The scent of someone who has already won.' },
]
